import { Music2, Pause, Play, RotateCcw, Square } from 'lucide-react';
import { formatTime, songDuration, songs } from '../lib/songs';
import type { PresetSong } from '../lib/songs';
import type { InstrumentId } from '../lib/music';
import type { PlayerSnapshot } from '../audio/song-player';
import { instrumentNoteName } from '../lib/music';

export function PresetPlayer({ instrument, song, state, speed, practice, onSong, onPlay, onPause, onStop, onRestart, onSpeed, onPractice, onTargetDown, onTargetUp }: {
  instrument: InstrumentId; song: PresetSong; state: PlayerSnapshot; speed: number; practice: boolean;
  onSong: (id: string) => void; onPlay: () => void; onPause: () => void; onStop: () => void; onRestart: () => void;
  onSpeed: (value: number) => void; onPractice: (value: boolean) => void; onTargetDown: () => void; onTargetUp: () => void;
}) {
  return <section className="preset-player" aria-labelledby="preset-title"><div className="preset-intro"><span className="preset-symbol"><Music2 size={19} /></span><div><h2 id="preset-title">Borrow a little momentum.</h2><p>Let your instrument play a melody.</p></div><span className="eyebrow">THE SONGBOOK</span></div>
    <div className="preset-main"><div className="song-select-wrap"><label htmlFor="preset-song">PRESET SONG</label><select id="preset-song" value={song.id} onChange={e => onSong(e.target.value)}>{['Original practice', 'Original film-inspired', 'Bollywood'].filter(collection => songs.some(s => s.collection === collection)).map(collection => <optgroup label={collection} key={collection}>{songs.filter(s => s.collection === collection).map(s => <option key={s.id} value={s.id}>{s.title} · {s.difficulty} · {formatTime(songDuration(s))}</option>)}</optgroup>)}</select><span className="song-attribution">{song.collection === 'Bollywood' ? song.license.attribution : 'Original composition'} <span>·</span> {song.collection}</span></div><div className="song-controls"><button className="song-play" aria-label={state.status === 'playing' ? 'Pause preset song' : state.status === 'paused' ? 'Resume preset song' : 'Play Preset Song'} onClick={state.status === 'playing' ? onPause : onPlay}>{state.status === 'playing' ? <Pause size={17} fill="currentColor" /> : <Play size={17} fill="currentColor" />}{state.status === 'playing' ? 'Pause' : state.status === 'paused' ? 'Resume' : 'Play song'}</button><button className="icon-button" aria-label="Stop preset song" onClick={onStop} disabled={state.status === 'idle'}><Square size={16} /></button><button className="icon-button" aria-label="Restart preset song" onClick={onRestart}><RotateCcw size={17} /></button></div><label className="song-speed">Tempo <select aria-label="Song tempo multiplier" value={speed} onChange={e => onSpeed(Number(e.target.value))}>{[0.5, 0.75, 1, 1.25, 1.5].map(n => <option key={n} value={n}>{n.toFixed(2).replace('.00', '')}×</option>)}</select></label></div>
    <div className="song-progress-row"><span>{formatTime(state.position / speed)}</span><div className="song-progress" role="progressbar" aria-label="Song progress" aria-valuemin={0} aria-valuemax={state.duration} aria-valuenow={state.position} aria-valuetext={`${formatTime(state.position / speed)} of ${formatTime(state.duration / speed)}`}><span style={{ width: `${state.position / state.duration * 100}%` }} /></div><span>{formatTime(state.duration / speed)}</span></div>
    <div className="practice-row"><label className="practice-toggle"><input type="checkbox" checked={practice} onChange={e => onPractice(e.target.checked)} /><span className="toggle-track"><span /></span>Practice mode <span className="practice-explain">· waits for your note</span></label>{practice && state.target !== null ? <button className="target-note" onPointerDown={e => { e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); onTargetDown(); }} onPointerUp={onTargetUp} onPointerCancel={onTargetUp} onLostPointerCapture={onTargetUp} onClick={e => { if (e.detail === 0) { onTargetDown(); setTimeout(onTargetUp, 250); } }}>Play {instrumentNoteName(instrument, state.target)} <kbd>Space</kbd> <span>{state.practiceIndex + 1}/{song.notes.length}</span></button> : <span className="preset-state">{state.status === 'complete' ? 'Nicely played. Again?' : state.status === 'paused' ? 'Paused, right where you left it.' : state.status === 'playing' ? 'Follow the highlighted notes.' : 'Original melodies. Your choice of sound.'}</span>}</div>
  </section>;
}
